language: 
    - cpp

compiler:
    - gcc

before_install:
    - "pwd"
    - sudo apt-get update
    - sudo apt-get install libgtest-dev

install:
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/"
    - "pwd"
    - "cd $TRAVIS_BUILD_DIR"
    - "pwd"
    - "sudo cmake --build . --target-all && sudo make"

script:
    - pwd
    - ls -al
