language: 
    - cpp

compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install libgtest-dev

install:
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ;"
    - "pwd && sudo cmake --build . && sudo make"

script:
    - pwd
    - ls -al
