# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/champ/Git/crows/opulence

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/champ/Git/crows/opulence

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/champ/Git/crows/opulence/CMakeFiles /home/champ/Git/crows/opulence/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/champ/Git/crows/opulence/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opulence

# Build rule for target.
opulence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opulence
.PHONY : opulence

# fast build rule for target.
opulence/fast:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/build
.PHONY : opulence/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f test/gtest-1.7.0/CMakeFiles/gtest.dir/build.make test/gtest-1.7.0/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f test/gtest-1.7.0/CMakeFiles/gtest_main.dir/build.make test/gtest-1.7.0/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

home/champ/Git/crows/main.o: home/champ/Git/crows/main.cpp.o
.PHONY : home/champ/Git/crows/main.o

# target to build an object file
home/champ/Git/crows/main.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/main.cpp.o
.PHONY : home/champ/Git/crows/main.cpp.o

home/champ/Git/crows/main.i: home/champ/Git/crows/main.cpp.i
.PHONY : home/champ/Git/crows/main.i

# target to preprocess a source file
home/champ/Git/crows/main.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/main.cpp.i
.PHONY : home/champ/Git/crows/main.cpp.i

home/champ/Git/crows/main.s: home/champ/Git/crows/main.cpp.s
.PHONY : home/champ/Git/crows/main.s

# target to generate assembly for a file
home/champ/Git/crows/main.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/main.cpp.s
.PHONY : home/champ/Git/crows/main.cpp.s

home/champ/Git/crows/src/controller/omnicontroller/OmniController.o: home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.o
.PHONY : home/champ/Git/crows/src/controller/omnicontroller/OmniController.o

# target to build an object file
home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.o
.PHONY : home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.o

home/champ/Git/crows/src/controller/omnicontroller/OmniController.i: home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.i
.PHONY : home/champ/Git/crows/src/controller/omnicontroller/OmniController.i

# target to preprocess a source file
home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.i
.PHONY : home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.i

home/champ/Git/crows/src/controller/omnicontroller/OmniController.s: home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.s
.PHONY : home/champ/Git/crows/src/controller/omnicontroller/OmniController.s

# target to generate assembly for a file
home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.s
.PHONY : home/champ/Git/crows/src/controller/omnicontroller/OmniController.cpp.s

home/champ/Git/crows/src/generator/SpriteGenerator.o: home/champ/Git/crows/src/generator/SpriteGenerator.cpp.o
.PHONY : home/champ/Git/crows/src/generator/SpriteGenerator.o

# target to build an object file
home/champ/Git/crows/src/generator/SpriteGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/generator/SpriteGenerator.cpp.o
.PHONY : home/champ/Git/crows/src/generator/SpriteGenerator.cpp.o

home/champ/Git/crows/src/generator/SpriteGenerator.i: home/champ/Git/crows/src/generator/SpriteGenerator.cpp.i
.PHONY : home/champ/Git/crows/src/generator/SpriteGenerator.i

# target to preprocess a source file
home/champ/Git/crows/src/generator/SpriteGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/generator/SpriteGenerator.cpp.i
.PHONY : home/champ/Git/crows/src/generator/SpriteGenerator.cpp.i

home/champ/Git/crows/src/generator/SpriteGenerator.s: home/champ/Git/crows/src/generator/SpriteGenerator.cpp.s
.PHONY : home/champ/Git/crows/src/generator/SpriteGenerator.s

# target to generate assembly for a file
home/champ/Git/crows/src/generator/SpriteGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/generator/SpriteGenerator.cpp.s
.PHONY : home/champ/Git/crows/src/generator/SpriteGenerator.cpp.s

home/champ/Git/crows/src/service/PathFinder.o: home/champ/Git/crows/src/service/PathFinder.cpp.o
.PHONY : home/champ/Git/crows/src/service/PathFinder.o

# target to build an object file
home/champ/Git/crows/src/service/PathFinder.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/service/PathFinder.cpp.o
.PHONY : home/champ/Git/crows/src/service/PathFinder.cpp.o

home/champ/Git/crows/src/service/PathFinder.i: home/champ/Git/crows/src/service/PathFinder.cpp.i
.PHONY : home/champ/Git/crows/src/service/PathFinder.i

# target to preprocess a source file
home/champ/Git/crows/src/service/PathFinder.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/service/PathFinder.cpp.i
.PHONY : home/champ/Git/crows/src/service/PathFinder.cpp.i

home/champ/Git/crows/src/service/PathFinder.s: home/champ/Git/crows/src/service/PathFinder.cpp.s
.PHONY : home/champ/Git/crows/src/service/PathFinder.s

# target to generate assembly for a file
home/champ/Git/crows/src/service/PathFinder.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/service/PathFinder.cpp.s
.PHONY : home/champ/Git/crows/src/service/PathFinder.cpp.s

home/champ/Git/crows/src/service/SpriteFinder.o: home/champ/Git/crows/src/service/SpriteFinder.cpp.o
.PHONY : home/champ/Git/crows/src/service/SpriteFinder.o

# target to build an object file
home/champ/Git/crows/src/service/SpriteFinder.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/service/SpriteFinder.cpp.o
.PHONY : home/champ/Git/crows/src/service/SpriteFinder.cpp.o

home/champ/Git/crows/src/service/SpriteFinder.i: home/champ/Git/crows/src/service/SpriteFinder.cpp.i
.PHONY : home/champ/Git/crows/src/service/SpriteFinder.i

# target to preprocess a source file
home/champ/Git/crows/src/service/SpriteFinder.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/service/SpriteFinder.cpp.i
.PHONY : home/champ/Git/crows/src/service/SpriteFinder.cpp.i

home/champ/Git/crows/src/service/SpriteFinder.s: home/champ/Git/crows/src/service/SpriteFinder.cpp.s
.PHONY : home/champ/Git/crows/src/service/SpriteFinder.s

# target to generate assembly for a file
home/champ/Git/crows/src/service/SpriteFinder.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/service/SpriteFinder.cpp.s
.PHONY : home/champ/Git/crows/src/service/SpriteFinder.cpp.s

home/champ/Git/crows/src/sprite/Sprite.o: home/champ/Git/crows/src/sprite/Sprite.cpp.o
.PHONY : home/champ/Git/crows/src/sprite/Sprite.o

# target to build an object file
home/champ/Git/crows/src/sprite/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/sprite/Sprite.cpp.o
.PHONY : home/champ/Git/crows/src/sprite/Sprite.cpp.o

home/champ/Git/crows/src/sprite/Sprite.i: home/champ/Git/crows/src/sprite/Sprite.cpp.i
.PHONY : home/champ/Git/crows/src/sprite/Sprite.i

# target to preprocess a source file
home/champ/Git/crows/src/sprite/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/sprite/Sprite.cpp.i
.PHONY : home/champ/Git/crows/src/sprite/Sprite.cpp.i

home/champ/Git/crows/src/sprite/Sprite.s: home/champ/Git/crows/src/sprite/Sprite.cpp.s
.PHONY : home/champ/Git/crows/src/sprite/Sprite.s

# target to generate assembly for a file
home/champ/Git/crows/src/sprite/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/home/champ/Git/crows/src/sprite/Sprite.cpp.s
.PHONY : home/champ/Git/crows/src/sprite/Sprite.cpp.s

opulence.o: opulence.cpp.o
.PHONY : opulence.o

# target to build an object file
opulence.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/opulence.cpp.o
.PHONY : opulence.cpp.o

opulence.i: opulence.cpp.i
.PHONY : opulence.i

# target to preprocess a source file
opulence.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/opulence.cpp.i
.PHONY : opulence.cpp.i

opulence.s: opulence.cpp.s
.PHONY : opulence.s

# target to generate assembly for a file
opulence.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/opulence.cpp.s
.PHONY : opulence.cpp.s

src/entity/Entity.o: src/entity/Entity.cpp.o
.PHONY : src/entity/Entity.o

# target to build an object file
src/entity/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/Entity.cpp.o
.PHONY : src/entity/Entity.cpp.o

src/entity/Entity.i: src/entity/Entity.cpp.i
.PHONY : src/entity/Entity.i

# target to preprocess a source file
src/entity/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/Entity.cpp.i
.PHONY : src/entity/Entity.cpp.i

src/entity/Entity.s: src/entity/Entity.cpp.s
.PHONY : src/entity/Entity.s

# target to generate assembly for a file
src/entity/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/Entity.cpp.s
.PHONY : src/entity/Entity.cpp.s

src/entity/animation/Animation.o: src/entity/animation/Animation.cpp.o
.PHONY : src/entity/animation/Animation.o

# target to build an object file
src/entity/animation/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/animation/Animation.cpp.o
.PHONY : src/entity/animation/Animation.cpp.o

src/entity/animation/Animation.i: src/entity/animation/Animation.cpp.i
.PHONY : src/entity/animation/Animation.i

# target to preprocess a source file
src/entity/animation/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/animation/Animation.cpp.i
.PHONY : src/entity/animation/Animation.cpp.i

src/entity/animation/Animation.s: src/entity/animation/Animation.cpp.s
.PHONY : src/entity/animation/Animation.s

# target to generate assembly for a file
src/entity/animation/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/animation/Animation.cpp.s
.PHONY : src/entity/animation/Animation.cpp.s

src/entity/camera/Camera.o: src/entity/camera/Camera.cpp.o
.PHONY : src/entity/camera/Camera.o

# target to build an object file
src/entity/camera/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/Camera.cpp.o
.PHONY : src/entity/camera/Camera.cpp.o

src/entity/camera/Camera.i: src/entity/camera/Camera.cpp.i
.PHONY : src/entity/camera/Camera.i

# target to preprocess a source file
src/entity/camera/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/Camera.cpp.i
.PHONY : src/entity/camera/Camera.cpp.i

src/entity/camera/Camera.s: src/entity/camera/Camera.cpp.s
.PHONY : src/entity/camera/Camera.s

# target to generate assembly for a file
src/entity/camera/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/Camera.cpp.s
.PHONY : src/entity/camera/Camera.cpp.s

src/entity/camera/RtsCamera.o: src/entity/camera/RtsCamera.cpp.o
.PHONY : src/entity/camera/RtsCamera.o

# target to build an object file
src/entity/camera/RtsCamera.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/RtsCamera.cpp.o
.PHONY : src/entity/camera/RtsCamera.cpp.o

src/entity/camera/RtsCamera.i: src/entity/camera/RtsCamera.cpp.i
.PHONY : src/entity/camera/RtsCamera.i

# target to preprocess a source file
src/entity/camera/RtsCamera.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/RtsCamera.cpp.i
.PHONY : src/entity/camera/RtsCamera.cpp.i

src/entity/camera/RtsCamera.s: src/entity/camera/RtsCamera.cpp.s
.PHONY : src/entity/camera/RtsCamera.s

# target to generate assembly for a file
src/entity/camera/RtsCamera.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/RtsCamera.cpp.s
.PHONY : src/entity/camera/RtsCamera.cpp.s

src/entity/light/DirectionalLight.o: src/entity/light/DirectionalLight.cpp.o
.PHONY : src/entity/light/DirectionalLight.o

# target to build an object file
src/entity/light/DirectionalLight.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/DirectionalLight.cpp.o
.PHONY : src/entity/light/DirectionalLight.cpp.o

src/entity/light/DirectionalLight.i: src/entity/light/DirectionalLight.cpp.i
.PHONY : src/entity/light/DirectionalLight.i

# target to preprocess a source file
src/entity/light/DirectionalLight.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/DirectionalLight.cpp.i
.PHONY : src/entity/light/DirectionalLight.cpp.i

src/entity/light/DirectionalLight.s: src/entity/light/DirectionalLight.cpp.s
.PHONY : src/entity/light/DirectionalLight.s

# target to generate assembly for a file
src/entity/light/DirectionalLight.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/DirectionalLight.cpp.s
.PHONY : src/entity/light/DirectionalLight.cpp.s

src/entity/light/Light.o: src/entity/light/Light.cpp.o
.PHONY : src/entity/light/Light.o

# target to build an object file
src/entity/light/Light.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/Light.cpp.o
.PHONY : src/entity/light/Light.cpp.o

src/entity/light/Light.i: src/entity/light/Light.cpp.i
.PHONY : src/entity/light/Light.i

# target to preprocess a source file
src/entity/light/Light.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/Light.cpp.i
.PHONY : src/entity/light/Light.cpp.i

src/entity/light/Light.s: src/entity/light/Light.cpp.s
.PHONY : src/entity/light/Light.s

# target to generate assembly for a file
src/entity/light/Light.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/Light.cpp.s
.PHONY : src/entity/light/Light.cpp.s

src/entity/light/PointLight.o: src/entity/light/PointLight.cpp.o
.PHONY : src/entity/light/PointLight.o

# target to build an object file
src/entity/light/PointLight.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/PointLight.cpp.o
.PHONY : src/entity/light/PointLight.cpp.o

src/entity/light/PointLight.i: src/entity/light/PointLight.cpp.i
.PHONY : src/entity/light/PointLight.i

# target to preprocess a source file
src/entity/light/PointLight.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/PointLight.cpp.i
.PHONY : src/entity/light/PointLight.cpp.i

src/entity/light/PointLight.s: src/entity/light/PointLight.cpp.s
.PHONY : src/entity/light/PointLight.s

# target to generate assembly for a file
src/entity/light/PointLight.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/PointLight.cpp.s
.PHONY : src/entity/light/PointLight.cpp.s

src/entity/model/Model.o: src/entity/model/Model.cpp.o
.PHONY : src/entity/model/Model.o

# target to build an object file
src/entity/model/Model.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/model/Model.cpp.o
.PHONY : src/entity/model/Model.cpp.o

src/entity/model/Model.i: src/entity/model/Model.cpp.i
.PHONY : src/entity/model/Model.i

# target to preprocess a source file
src/entity/model/Model.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/model/Model.cpp.i
.PHONY : src/entity/model/Model.cpp.i

src/entity/model/Model.s: src/entity/model/Model.cpp.s
.PHONY : src/entity/model/Model.s

# target to generate assembly for a file
src/entity/model/Model.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/model/Model.cpp.s
.PHONY : src/entity/model/Model.cpp.s

src/factory/CameraFactory.o: src/factory/CameraFactory.cpp.o
.PHONY : src/factory/CameraFactory.o

# target to build an object file
src/factory/CameraFactory.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/CameraFactory.cpp.o
.PHONY : src/factory/CameraFactory.cpp.o

src/factory/CameraFactory.i: src/factory/CameraFactory.cpp.i
.PHONY : src/factory/CameraFactory.i

# target to preprocess a source file
src/factory/CameraFactory.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/CameraFactory.cpp.i
.PHONY : src/factory/CameraFactory.cpp.i

src/factory/CameraFactory.s: src/factory/CameraFactory.cpp.s
.PHONY : src/factory/CameraFactory.s

# target to generate assembly for a file
src/factory/CameraFactory.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/CameraFactory.cpp.s
.PHONY : src/factory/CameraFactory.cpp.s

src/factory/LightFactory.o: src/factory/LightFactory.cpp.o
.PHONY : src/factory/LightFactory.o

# target to build an object file
src/factory/LightFactory.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/LightFactory.cpp.o
.PHONY : src/factory/LightFactory.cpp.o

src/factory/LightFactory.i: src/factory/LightFactory.cpp.i
.PHONY : src/factory/LightFactory.i

# target to preprocess a source file
src/factory/LightFactory.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/LightFactory.cpp.i
.PHONY : src/factory/LightFactory.cpp.i

src/factory/LightFactory.s: src/factory/LightFactory.cpp.s
.PHONY : src/factory/LightFactory.s

# target to generate assembly for a file
src/factory/LightFactory.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/LightFactory.cpp.s
.PHONY : src/factory/LightFactory.cpp.s

src/factory/ModelFactory.o: src/factory/ModelFactory.cpp.o
.PHONY : src/factory/ModelFactory.o

# target to build an object file
src/factory/ModelFactory.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/ModelFactory.cpp.o
.PHONY : src/factory/ModelFactory.cpp.o

src/factory/ModelFactory.i: src/factory/ModelFactory.cpp.i
.PHONY : src/factory/ModelFactory.i

# target to preprocess a source file
src/factory/ModelFactory.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/ModelFactory.cpp.i
.PHONY : src/factory/ModelFactory.cpp.i

src/factory/ModelFactory.s: src/factory/ModelFactory.cpp.s
.PHONY : src/factory/ModelFactory.s

# target to generate assembly for a file
src/factory/ModelFactory.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/ModelFactory.cpp.s
.PHONY : src/factory/ModelFactory.cpp.s

src/loader/ObjLoader.o: src/loader/ObjLoader.cpp.o
.PHONY : src/loader/ObjLoader.o

# target to build an object file
src/loader/ObjLoader.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ObjLoader.cpp.o
.PHONY : src/loader/ObjLoader.cpp.o

src/loader/ObjLoader.i: src/loader/ObjLoader.cpp.i
.PHONY : src/loader/ObjLoader.i

# target to preprocess a source file
src/loader/ObjLoader.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ObjLoader.cpp.i
.PHONY : src/loader/ObjLoader.cpp.i

src/loader/ObjLoader.s: src/loader/ObjLoader.cpp.s
.PHONY : src/loader/ObjLoader.s

# target to generate assembly for a file
src/loader/ObjLoader.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ObjLoader.cpp.s
.PHONY : src/loader/ObjLoader.cpp.s

src/loader/ShaderLoader.o: src/loader/ShaderLoader.cpp.o
.PHONY : src/loader/ShaderLoader.o

# target to build an object file
src/loader/ShaderLoader.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ShaderLoader.cpp.o
.PHONY : src/loader/ShaderLoader.cpp.o

src/loader/ShaderLoader.i: src/loader/ShaderLoader.cpp.i
.PHONY : src/loader/ShaderLoader.i

# target to preprocess a source file
src/loader/ShaderLoader.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ShaderLoader.cpp.i
.PHONY : src/loader/ShaderLoader.cpp.i

src/loader/ShaderLoader.s: src/loader/ShaderLoader.cpp.s
.PHONY : src/loader/ShaderLoader.s

# target to generate assembly for a file
src/loader/ShaderLoader.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ShaderLoader.cpp.s
.PHONY : src/loader/ShaderLoader.cpp.s

src/service/BufferCourier.o: src/service/BufferCourier.cpp.o
.PHONY : src/service/BufferCourier.o

# target to build an object file
src/service/BufferCourier.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/BufferCourier.cpp.o
.PHONY : src/service/BufferCourier.cpp.o

src/service/BufferCourier.i: src/service/BufferCourier.cpp.i
.PHONY : src/service/BufferCourier.i

# target to preprocess a source file
src/service/BufferCourier.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/BufferCourier.cpp.i
.PHONY : src/service/BufferCourier.cpp.i

src/service/BufferCourier.s: src/service/BufferCourier.cpp.s
.PHONY : src/service/BufferCourier.s

# target to generate assembly for a file
src/service/BufferCourier.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/BufferCourier.cpp.s
.PHONY : src/service/BufferCourier.cpp.s

src/service/GLManager.o: src/service/GLManager.cpp.o
.PHONY : src/service/GLManager.o

# target to build an object file
src/service/GLManager.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/GLManager.cpp.o
.PHONY : src/service/GLManager.cpp.o

src/service/GLManager.i: src/service/GLManager.cpp.i
.PHONY : src/service/GLManager.i

# target to preprocess a source file
src/service/GLManager.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/GLManager.cpp.i
.PHONY : src/service/GLManager.cpp.i

src/service/GLManager.s: src/service/GLManager.cpp.s
.PHONY : src/service/GLManager.s

# target to generate assembly for a file
src/service/GLManager.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/GLManager.cpp.s
.PHONY : src/service/GLManager.cpp.s

src/service/TimeManager.o: src/service/TimeManager.cpp.o
.PHONY : src/service/TimeManager.o

# target to build an object file
src/service/TimeManager.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/TimeManager.cpp.o
.PHONY : src/service/TimeManager.cpp.o

src/service/TimeManager.i: src/service/TimeManager.cpp.i
.PHONY : src/service/TimeManager.i

# target to preprocess a source file
src/service/TimeManager.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/TimeManager.cpp.i
.PHONY : src/service/TimeManager.cpp.i

src/service/TimeManager.s: src/service/TimeManager.cpp.s
.PHONY : src/service/TimeManager.s

# target to generate assembly for a file
src/service/TimeManager.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/TimeManager.cpp.s
.PHONY : src/service/TimeManager.cpp.s

test/entity/ModelTest.o: test/entity/ModelTest.cpp.o
.PHONY : test/entity/ModelTest.o

# target to build an object file
test/entity/ModelTest.cpp.o:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/test/entity/ModelTest.cpp.o
.PHONY : test/entity/ModelTest.cpp.o

test/entity/ModelTest.i: test/entity/ModelTest.cpp.i
.PHONY : test/entity/ModelTest.i

# target to preprocess a source file
test/entity/ModelTest.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/test/entity/ModelTest.cpp.i
.PHONY : test/entity/ModelTest.cpp.i

test/entity/ModelTest.s: test/entity/ModelTest.cpp.s
.PHONY : test/entity/ModelTest.s

# target to generate assembly for a file
test/entity/ModelTest.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/test/entity/ModelTest.cpp.s
.PHONY : test/entity/ModelTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... opulence"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... home/champ/Git/crows/main.o"
	@echo "... home/champ/Git/crows/main.i"
	@echo "... home/champ/Git/crows/main.s"
	@echo "... home/champ/Git/crows/src/controller/omnicontroller/OmniController.o"
	@echo "... home/champ/Git/crows/src/controller/omnicontroller/OmniController.i"
	@echo "... home/champ/Git/crows/src/controller/omnicontroller/OmniController.s"
	@echo "... home/champ/Git/crows/src/generator/SpriteGenerator.o"
	@echo "... home/champ/Git/crows/src/generator/SpriteGenerator.i"
	@echo "... home/champ/Git/crows/src/generator/SpriteGenerator.s"
	@echo "... home/champ/Git/crows/src/service/PathFinder.o"
	@echo "... home/champ/Git/crows/src/service/PathFinder.i"
	@echo "... home/champ/Git/crows/src/service/PathFinder.s"
	@echo "... home/champ/Git/crows/src/service/SpriteFinder.o"
	@echo "... home/champ/Git/crows/src/service/SpriteFinder.i"
	@echo "... home/champ/Git/crows/src/service/SpriteFinder.s"
	@echo "... home/champ/Git/crows/src/sprite/Sprite.o"
	@echo "... home/champ/Git/crows/src/sprite/Sprite.i"
	@echo "... home/champ/Git/crows/src/sprite/Sprite.s"
	@echo "... opulence.o"
	@echo "... opulence.i"
	@echo "... opulence.s"
	@echo "... src/entity/Entity.o"
	@echo "... src/entity/Entity.i"
	@echo "... src/entity/Entity.s"
	@echo "... src/entity/animation/Animation.o"
	@echo "... src/entity/animation/Animation.i"
	@echo "... src/entity/animation/Animation.s"
	@echo "... src/entity/camera/Camera.o"
	@echo "... src/entity/camera/Camera.i"
	@echo "... src/entity/camera/Camera.s"
	@echo "... src/entity/camera/RtsCamera.o"
	@echo "... src/entity/camera/RtsCamera.i"
	@echo "... src/entity/camera/RtsCamera.s"
	@echo "... src/entity/light/DirectionalLight.o"
	@echo "... src/entity/light/DirectionalLight.i"
	@echo "... src/entity/light/DirectionalLight.s"
	@echo "... src/entity/light/Light.o"
	@echo "... src/entity/light/Light.i"
	@echo "... src/entity/light/Light.s"
	@echo "... src/entity/light/PointLight.o"
	@echo "... src/entity/light/PointLight.i"
	@echo "... src/entity/light/PointLight.s"
	@echo "... src/entity/model/Model.o"
	@echo "... src/entity/model/Model.i"
	@echo "... src/entity/model/Model.s"
	@echo "... src/factory/CameraFactory.o"
	@echo "... src/factory/CameraFactory.i"
	@echo "... src/factory/CameraFactory.s"
	@echo "... src/factory/LightFactory.o"
	@echo "... src/factory/LightFactory.i"
	@echo "... src/factory/LightFactory.s"
	@echo "... src/factory/ModelFactory.o"
	@echo "... src/factory/ModelFactory.i"
	@echo "... src/factory/ModelFactory.s"
	@echo "... src/loader/ObjLoader.o"
	@echo "... src/loader/ObjLoader.i"
	@echo "... src/loader/ObjLoader.s"
	@echo "... src/loader/ShaderLoader.o"
	@echo "... src/loader/ShaderLoader.i"
	@echo "... src/loader/ShaderLoader.s"
	@echo "... src/service/BufferCourier.o"
	@echo "... src/service/BufferCourier.i"
	@echo "... src/service/BufferCourier.s"
	@echo "... src/service/GLManager.o"
	@echo "... src/service/GLManager.i"
	@echo "... src/service/GLManager.s"
	@echo "... src/service/TimeManager.o"
	@echo "... src/service/TimeManager.i"
	@echo "... src/service/TimeManager.s"
	@echo "... test/entity/ModelTest.o"
	@echo "... test/entity/ModelTest.i"
	@echo "... test/entity/ModelTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

