# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files (x86)/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files (x86)/CMake/bin/cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/champ/Git/crows/opulence

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/champ/Git/crows/opulence

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files (x86)/CMake/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files (x86)/CMake/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/champ/Git/crows/opulence/CMakeFiles C:/Users/champ/Git/crows/opulence/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/champ/Git/crows/opulence/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opulence

# Build rule for target.
opulence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opulence
.PHONY : opulence

# fast build rule for target.
opulence/fast:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/build
.PHONY : opulence/fast

C_/Users/champ/Git/crows/main.obj: C_/Users/champ/Git/crows/main.cpp.obj

.PHONY : C_/Users/champ/Git/crows/main.obj

# target to build an object file
C_/Users/champ/Git/crows/main.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/main.cpp.obj
.PHONY : C_/Users/champ/Git/crows/main.cpp.obj

C_/Users/champ/Git/crows/main.i: C_/Users/champ/Git/crows/main.cpp.i

.PHONY : C_/Users/champ/Git/crows/main.i

# target to preprocess a source file
C_/Users/champ/Git/crows/main.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/main.cpp.i
.PHONY : C_/Users/champ/Git/crows/main.cpp.i

C_/Users/champ/Git/crows/main.s: C_/Users/champ/Git/crows/main.cpp.s

.PHONY : C_/Users/champ/Git/crows/main.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/main.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/main.cpp.s
.PHONY : C_/Users/champ/Git/crows/main.cpp.s

C_/Users/champ/Git/crows/src/ai/Ai.obj: C_/Users/champ/Git/crows/src/ai/Ai.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/ai/Ai.obj

# target to build an object file
C_/Users/champ/Git/crows/src/ai/Ai.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/ai/Ai.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/ai/Ai.cpp.obj

C_/Users/champ/Git/crows/src/ai/Ai.i: C_/Users/champ/Git/crows/src/ai/Ai.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/ai/Ai.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/ai/Ai.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/ai/Ai.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/ai/Ai.cpp.i

C_/Users/champ/Git/crows/src/ai/Ai.s: C_/Users/champ/Git/crows/src/ai/Ai.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/ai/Ai.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/ai/Ai.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/ai/Ai.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/ai/Ai.cpp.s

C_/Users/champ/Git/crows/src/anima/interface/button/Button.obj: C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/button/Button.obj

# target to build an object file
C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.obj

C_/Users/champ/Git/crows/src/anima/interface/button/Button.i: C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/button/Button.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.i

C_/Users/champ/Git/crows/src/anima/interface/button/Button.s: C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/button/Button.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/button/Button.cpp.s

C_/Users/champ/Git/crows/src/anima/interface/character/Character.obj: C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/Character.obj

# target to build an object file
C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.obj

C_/Users/champ/Git/crows/src/anima/interface/character/Character.i: C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/Character.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.i

C_/Users/champ/Git/crows/src/anima/interface/character/Character.s: C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/Character.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/Character.cpp.s

C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.obj: C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.obj

# target to build an object file
C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.obj

C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.i: C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.i

C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.s: C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.cpp.s

C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.obj: C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.obj

# target to build an object file
C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.obj

C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.i: C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.i

C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.s: C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.cpp.s

C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.obj: C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.obj

# target to build an object file
C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.obj

C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.i: C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.i

C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.s: C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.cpp.s

C_/Users/champ/Git/crows/src/generator/SpriteGenerator.obj: C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/generator/SpriteGenerator.obj

# target to build an object file
C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.obj

C_/Users/champ/Git/crows/src/generator/SpriteGenerator.i: C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/generator/SpriteGenerator.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.i

C_/Users/champ/Git/crows/src/generator/SpriteGenerator.s: C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/generator/SpriteGenerator.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/generator/SpriteGenerator.cpp.s

C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.obj: C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.obj

# target to build an object file
C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.obj

C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.i: C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.i

C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.s: C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.cpp.s

C_/Users/champ/Git/crows/src/habitat/tree/Tree.obj: C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/habitat/tree/Tree.obj

# target to build an object file
C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.obj

C_/Users/champ/Git/crows/src/habitat/tree/Tree.i: C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/habitat/tree/Tree.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.i

C_/Users/champ/Git/crows/src/habitat/tree/Tree.s: C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/habitat/tree/Tree.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/habitat/tree/Tree.cpp.s

C_/Users/champ/Git/crows/src/service/Manipulator.obj: C_/Users/champ/Git/crows/src/service/Manipulator.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/service/Manipulator.obj

# target to build an object file
C_/Users/champ/Git/crows/src/service/Manipulator.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/service/Manipulator.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/service/Manipulator.cpp.obj

C_/Users/champ/Git/crows/src/service/Manipulator.i: C_/Users/champ/Git/crows/src/service/Manipulator.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/service/Manipulator.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/service/Manipulator.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/service/Manipulator.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/service/Manipulator.cpp.i

C_/Users/champ/Git/crows/src/service/Manipulator.s: C_/Users/champ/Git/crows/src/service/Manipulator.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/service/Manipulator.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/service/Manipulator.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/service/Manipulator.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/service/Manipulator.cpp.s

C_/Users/champ/Git/crows/src/service/PathFinder.obj: C_/Users/champ/Git/crows/src/service/PathFinder.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/service/PathFinder.obj

# target to build an object file
C_/Users/champ/Git/crows/src/service/PathFinder.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/service/PathFinder.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/service/PathFinder.cpp.obj

C_/Users/champ/Git/crows/src/service/PathFinder.i: C_/Users/champ/Git/crows/src/service/PathFinder.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/service/PathFinder.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/service/PathFinder.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/service/PathFinder.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/service/PathFinder.cpp.i

C_/Users/champ/Git/crows/src/service/PathFinder.s: C_/Users/champ/Git/crows/src/service/PathFinder.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/service/PathFinder.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/service/PathFinder.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/service/PathFinder.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/service/PathFinder.cpp.s

C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.obj: C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.obj

# target to build an object file
C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.obj

C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.i: C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.i

C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.s: C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.cpp.s

C_/Users/champ/Git/crows/src/sprite/Sprite.obj: C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/sprite/Sprite.obj

# target to build an object file
C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.obj

C_/Users/champ/Git/crows/src/sprite/Sprite.i: C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/sprite/Sprite.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.i

C_/Users/champ/Git/crows/src/sprite/Sprite.s: C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/sprite/Sprite.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/sprite/Sprite.cpp.s

C_/Users/champ/Git/crows/src/utility/DayManager.obj: C_/Users/champ/Git/crows/src/utility/DayManager.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/utility/DayManager.obj

# target to build an object file
C_/Users/champ/Git/crows/src/utility/DayManager.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/utility/DayManager.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/utility/DayManager.cpp.obj

C_/Users/champ/Git/crows/src/utility/DayManager.i: C_/Users/champ/Git/crows/src/utility/DayManager.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/utility/DayManager.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/utility/DayManager.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/utility/DayManager.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/utility/DayManager.cpp.i

C_/Users/champ/Git/crows/src/utility/DayManager.s: C_/Users/champ/Git/crows/src/utility/DayManager.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/utility/DayManager.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/utility/DayManager.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/utility/DayManager.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/utility/DayManager.cpp.s

C_/Users/champ/Git/crows/src/utility/LevelMaker.obj: C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.obj

.PHONY : C_/Users/champ/Git/crows/src/utility/LevelMaker.obj

# target to build an object file
C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.obj
.PHONY : C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.obj

C_/Users/champ/Git/crows/src/utility/LevelMaker.i: C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.i

.PHONY : C_/Users/champ/Git/crows/src/utility/LevelMaker.i

# target to preprocess a source file
C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.i
.PHONY : C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.i

C_/Users/champ/Git/crows/src/utility/LevelMaker.s: C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.s

.PHONY : C_/Users/champ/Git/crows/src/utility/LevelMaker.s

# target to generate assembly for a file
C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.s
.PHONY : C_/Users/champ/Git/crows/src/utility/LevelMaker.cpp.s

opulence.obj: opulence.cpp.obj

.PHONY : opulence.obj

# target to build an object file
opulence.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/opulence.cpp.obj
.PHONY : opulence.cpp.obj

opulence.i: opulence.cpp.i

.PHONY : opulence.i

# target to preprocess a source file
opulence.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/opulence.cpp.i
.PHONY : opulence.cpp.i

opulence.s: opulence.cpp.s

.PHONY : opulence.s

# target to generate assembly for a file
opulence.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/opulence.cpp.s
.PHONY : opulence.cpp.s

src/entity/Entity.obj: src/entity/Entity.cpp.obj

.PHONY : src/entity/Entity.obj

# target to build an object file
src/entity/Entity.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/Entity.cpp.obj
.PHONY : src/entity/Entity.cpp.obj

src/entity/Entity.i: src/entity/Entity.cpp.i

.PHONY : src/entity/Entity.i

# target to preprocess a source file
src/entity/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/Entity.cpp.i
.PHONY : src/entity/Entity.cpp.i

src/entity/Entity.s: src/entity/Entity.cpp.s

.PHONY : src/entity/Entity.s

# target to generate assembly for a file
src/entity/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/Entity.cpp.s
.PHONY : src/entity/Entity.cpp.s

src/entity/animation/Animation.obj: src/entity/animation/Animation.cpp.obj

.PHONY : src/entity/animation/Animation.obj

# target to build an object file
src/entity/animation/Animation.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/animation/Animation.cpp.obj
.PHONY : src/entity/animation/Animation.cpp.obj

src/entity/animation/Animation.i: src/entity/animation/Animation.cpp.i

.PHONY : src/entity/animation/Animation.i

# target to preprocess a source file
src/entity/animation/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/animation/Animation.cpp.i
.PHONY : src/entity/animation/Animation.cpp.i

src/entity/animation/Animation.s: src/entity/animation/Animation.cpp.s

.PHONY : src/entity/animation/Animation.s

# target to generate assembly for a file
src/entity/animation/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/animation/Animation.cpp.s
.PHONY : src/entity/animation/Animation.cpp.s

src/entity/camera/Camera.obj: src/entity/camera/Camera.cpp.obj

.PHONY : src/entity/camera/Camera.obj

# target to build an object file
src/entity/camera/Camera.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/Camera.cpp.obj
.PHONY : src/entity/camera/Camera.cpp.obj

src/entity/camera/Camera.i: src/entity/camera/Camera.cpp.i

.PHONY : src/entity/camera/Camera.i

# target to preprocess a source file
src/entity/camera/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/Camera.cpp.i
.PHONY : src/entity/camera/Camera.cpp.i

src/entity/camera/Camera.s: src/entity/camera/Camera.cpp.s

.PHONY : src/entity/camera/Camera.s

# target to generate assembly for a file
src/entity/camera/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/Camera.cpp.s
.PHONY : src/entity/camera/Camera.cpp.s

src/entity/camera/RtsCamera.obj: src/entity/camera/RtsCamera.cpp.obj

.PHONY : src/entity/camera/RtsCamera.obj

# target to build an object file
src/entity/camera/RtsCamera.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/RtsCamera.cpp.obj
.PHONY : src/entity/camera/RtsCamera.cpp.obj

src/entity/camera/RtsCamera.i: src/entity/camera/RtsCamera.cpp.i

.PHONY : src/entity/camera/RtsCamera.i

# target to preprocess a source file
src/entity/camera/RtsCamera.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/RtsCamera.cpp.i
.PHONY : src/entity/camera/RtsCamera.cpp.i

src/entity/camera/RtsCamera.s: src/entity/camera/RtsCamera.cpp.s

.PHONY : src/entity/camera/RtsCamera.s

# target to generate assembly for a file
src/entity/camera/RtsCamera.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/camera/RtsCamera.cpp.s
.PHONY : src/entity/camera/RtsCamera.cpp.s

src/entity/light/DirectionalLight.obj: src/entity/light/DirectionalLight.cpp.obj

.PHONY : src/entity/light/DirectionalLight.obj

# target to build an object file
src/entity/light/DirectionalLight.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/DirectionalLight.cpp.obj
.PHONY : src/entity/light/DirectionalLight.cpp.obj

src/entity/light/DirectionalLight.i: src/entity/light/DirectionalLight.cpp.i

.PHONY : src/entity/light/DirectionalLight.i

# target to preprocess a source file
src/entity/light/DirectionalLight.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/DirectionalLight.cpp.i
.PHONY : src/entity/light/DirectionalLight.cpp.i

src/entity/light/DirectionalLight.s: src/entity/light/DirectionalLight.cpp.s

.PHONY : src/entity/light/DirectionalLight.s

# target to generate assembly for a file
src/entity/light/DirectionalLight.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/DirectionalLight.cpp.s
.PHONY : src/entity/light/DirectionalLight.cpp.s

src/entity/light/Light.obj: src/entity/light/Light.cpp.obj

.PHONY : src/entity/light/Light.obj

# target to build an object file
src/entity/light/Light.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/Light.cpp.obj
.PHONY : src/entity/light/Light.cpp.obj

src/entity/light/Light.i: src/entity/light/Light.cpp.i

.PHONY : src/entity/light/Light.i

# target to preprocess a source file
src/entity/light/Light.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/Light.cpp.i
.PHONY : src/entity/light/Light.cpp.i

src/entity/light/Light.s: src/entity/light/Light.cpp.s

.PHONY : src/entity/light/Light.s

# target to generate assembly for a file
src/entity/light/Light.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/Light.cpp.s
.PHONY : src/entity/light/Light.cpp.s

src/entity/light/PointLight.obj: src/entity/light/PointLight.cpp.obj

.PHONY : src/entity/light/PointLight.obj

# target to build an object file
src/entity/light/PointLight.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/PointLight.cpp.obj
.PHONY : src/entity/light/PointLight.cpp.obj

src/entity/light/PointLight.i: src/entity/light/PointLight.cpp.i

.PHONY : src/entity/light/PointLight.i

# target to preprocess a source file
src/entity/light/PointLight.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/PointLight.cpp.i
.PHONY : src/entity/light/PointLight.cpp.i

src/entity/light/PointLight.s: src/entity/light/PointLight.cpp.s

.PHONY : src/entity/light/PointLight.s

# target to generate assembly for a file
src/entity/light/PointLight.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/light/PointLight.cpp.s
.PHONY : src/entity/light/PointLight.cpp.s

src/entity/model/Model.obj: src/entity/model/Model.cpp.obj

.PHONY : src/entity/model/Model.obj

# target to build an object file
src/entity/model/Model.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/model/Model.cpp.obj
.PHONY : src/entity/model/Model.cpp.obj

src/entity/model/Model.i: src/entity/model/Model.cpp.i

.PHONY : src/entity/model/Model.i

# target to preprocess a source file
src/entity/model/Model.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/model/Model.cpp.i
.PHONY : src/entity/model/Model.cpp.i

src/entity/model/Model.s: src/entity/model/Model.cpp.s

.PHONY : src/entity/model/Model.s

# target to generate assembly for a file
src/entity/model/Model.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/entity/model/Model.cpp.s
.PHONY : src/entity/model/Model.cpp.s

src/factory/CameraFactory.obj: src/factory/CameraFactory.cpp.obj

.PHONY : src/factory/CameraFactory.obj

# target to build an object file
src/factory/CameraFactory.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/CameraFactory.cpp.obj
.PHONY : src/factory/CameraFactory.cpp.obj

src/factory/CameraFactory.i: src/factory/CameraFactory.cpp.i

.PHONY : src/factory/CameraFactory.i

# target to preprocess a source file
src/factory/CameraFactory.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/CameraFactory.cpp.i
.PHONY : src/factory/CameraFactory.cpp.i

src/factory/CameraFactory.s: src/factory/CameraFactory.cpp.s

.PHONY : src/factory/CameraFactory.s

# target to generate assembly for a file
src/factory/CameraFactory.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/CameraFactory.cpp.s
.PHONY : src/factory/CameraFactory.cpp.s

src/factory/LightFactory.obj: src/factory/LightFactory.cpp.obj

.PHONY : src/factory/LightFactory.obj

# target to build an object file
src/factory/LightFactory.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/LightFactory.cpp.obj
.PHONY : src/factory/LightFactory.cpp.obj

src/factory/LightFactory.i: src/factory/LightFactory.cpp.i

.PHONY : src/factory/LightFactory.i

# target to preprocess a source file
src/factory/LightFactory.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/LightFactory.cpp.i
.PHONY : src/factory/LightFactory.cpp.i

src/factory/LightFactory.s: src/factory/LightFactory.cpp.s

.PHONY : src/factory/LightFactory.s

# target to generate assembly for a file
src/factory/LightFactory.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/LightFactory.cpp.s
.PHONY : src/factory/LightFactory.cpp.s

src/factory/ModelFactory.obj: src/factory/ModelFactory.cpp.obj

.PHONY : src/factory/ModelFactory.obj

# target to build an object file
src/factory/ModelFactory.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/ModelFactory.cpp.obj
.PHONY : src/factory/ModelFactory.cpp.obj

src/factory/ModelFactory.i: src/factory/ModelFactory.cpp.i

.PHONY : src/factory/ModelFactory.i

# target to preprocess a source file
src/factory/ModelFactory.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/ModelFactory.cpp.i
.PHONY : src/factory/ModelFactory.cpp.i

src/factory/ModelFactory.s: src/factory/ModelFactory.cpp.s

.PHONY : src/factory/ModelFactory.s

# target to generate assembly for a file
src/factory/ModelFactory.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/factory/ModelFactory.cpp.s
.PHONY : src/factory/ModelFactory.cpp.s

src/loader/ObjLoader.obj: src/loader/ObjLoader.cpp.obj

.PHONY : src/loader/ObjLoader.obj

# target to build an object file
src/loader/ObjLoader.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ObjLoader.cpp.obj
.PHONY : src/loader/ObjLoader.cpp.obj

src/loader/ObjLoader.i: src/loader/ObjLoader.cpp.i

.PHONY : src/loader/ObjLoader.i

# target to preprocess a source file
src/loader/ObjLoader.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ObjLoader.cpp.i
.PHONY : src/loader/ObjLoader.cpp.i

src/loader/ObjLoader.s: src/loader/ObjLoader.cpp.s

.PHONY : src/loader/ObjLoader.s

# target to generate assembly for a file
src/loader/ObjLoader.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ObjLoader.cpp.s
.PHONY : src/loader/ObjLoader.cpp.s

src/loader/ShaderLoader.obj: src/loader/ShaderLoader.cpp.obj

.PHONY : src/loader/ShaderLoader.obj

# target to build an object file
src/loader/ShaderLoader.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ShaderLoader.cpp.obj
.PHONY : src/loader/ShaderLoader.cpp.obj

src/loader/ShaderLoader.i: src/loader/ShaderLoader.cpp.i

.PHONY : src/loader/ShaderLoader.i

# target to preprocess a source file
src/loader/ShaderLoader.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ShaderLoader.cpp.i
.PHONY : src/loader/ShaderLoader.cpp.i

src/loader/ShaderLoader.s: src/loader/ShaderLoader.cpp.s

.PHONY : src/loader/ShaderLoader.s

# target to generate assembly for a file
src/loader/ShaderLoader.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/loader/ShaderLoader.cpp.s
.PHONY : src/loader/ShaderLoader.cpp.s

src/service/BufferCourier.obj: src/service/BufferCourier.cpp.obj

.PHONY : src/service/BufferCourier.obj

# target to build an object file
src/service/BufferCourier.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/BufferCourier.cpp.obj
.PHONY : src/service/BufferCourier.cpp.obj

src/service/BufferCourier.i: src/service/BufferCourier.cpp.i

.PHONY : src/service/BufferCourier.i

# target to preprocess a source file
src/service/BufferCourier.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/BufferCourier.cpp.i
.PHONY : src/service/BufferCourier.cpp.i

src/service/BufferCourier.s: src/service/BufferCourier.cpp.s

.PHONY : src/service/BufferCourier.s

# target to generate assembly for a file
src/service/BufferCourier.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/BufferCourier.cpp.s
.PHONY : src/service/BufferCourier.cpp.s

src/service/GLManager.obj: src/service/GLManager.cpp.obj

.PHONY : src/service/GLManager.obj

# target to build an object file
src/service/GLManager.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/GLManager.cpp.obj
.PHONY : src/service/GLManager.cpp.obj

src/service/GLManager.i: src/service/GLManager.cpp.i

.PHONY : src/service/GLManager.i

# target to preprocess a source file
src/service/GLManager.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/GLManager.cpp.i
.PHONY : src/service/GLManager.cpp.i

src/service/GLManager.s: src/service/GLManager.cpp.s

.PHONY : src/service/GLManager.s

# target to generate assembly for a file
src/service/GLManager.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/GLManager.cpp.s
.PHONY : src/service/GLManager.cpp.s

src/service/TimeManager.obj: src/service/TimeManager.cpp.obj

.PHONY : src/service/TimeManager.obj

# target to build an object file
src/service/TimeManager.cpp.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/TimeManager.cpp.obj
.PHONY : src/service/TimeManager.cpp.obj

src/service/TimeManager.i: src/service/TimeManager.cpp.i

.PHONY : src/service/TimeManager.i

# target to preprocess a source file
src/service/TimeManager.cpp.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/TimeManager.cpp.i
.PHONY : src/service/TimeManager.cpp.i

src/service/TimeManager.s: src/service/TimeManager.cpp.s

.PHONY : src/service/TimeManager.s

# target to generate assembly for a file
src/service/TimeManager.cpp.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/TimeManager.cpp.s
.PHONY : src/service/TimeManager.cpp.s

src/service/glew/glew.obj: src/service/glew/glew.c.obj

.PHONY : src/service/glew/glew.obj

# target to build an object file
src/service/glew/glew.c.obj:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/glew/glew.c.obj
.PHONY : src/service/glew/glew.c.obj

src/service/glew/glew.i: src/service/glew/glew.c.i

.PHONY : src/service/glew/glew.i

# target to preprocess a source file
src/service/glew/glew.c.i:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/glew/glew.c.i
.PHONY : src/service/glew/glew.c.i

src/service/glew/glew.s: src/service/glew/glew.c.s

.PHONY : src/service/glew/glew.s

# target to generate assembly for a file
src/service/glew/glew.c.s:
	$(MAKE) -f CMakeFiles/opulence.dir/build.make CMakeFiles/opulence.dir/src/service/glew/glew.c.s
.PHONY : src/service/glew/glew.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... opulence"
	@echo "... rebuild_cache"
	@echo "... C_/Users/champ/Git/crows/main.obj"
	@echo "... C_/Users/champ/Git/crows/main.i"
	@echo "... C_/Users/champ/Git/crows/main.s"
	@echo "... C_/Users/champ/Git/crows/src/ai/Ai.obj"
	@echo "... C_/Users/champ/Git/crows/src/ai/Ai.i"
	@echo "... C_/Users/champ/Git/crows/src/ai/Ai.s"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/button/Button.obj"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/button/Button.i"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/button/Button.s"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/character/Character.obj"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/character/Character.i"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/character/Character.s"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.obj"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.i"
	@echo "... C_/Users/champ/Git/crows/src/anima/interface/character/CharacterSet.s"
	@echo "... C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.obj"
	@echo "... C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.i"
	@echo "... C_/Users/champ/Git/crows/src/controller/standardcontroller/StandardController.s"
	@echo "... C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.obj"
	@echo "... C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.i"
	@echo "... C_/Users/champ/Git/crows/src/generator/InterfaceGenerator.s"
	@echo "... C_/Users/champ/Git/crows/src/generator/SpriteGenerator.obj"
	@echo "... C_/Users/champ/Git/crows/src/generator/SpriteGenerator.i"
	@echo "... C_/Users/champ/Git/crows/src/generator/SpriteGenerator.s"
	@echo "... C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.obj"
	@echo "... C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.i"
	@echo "... C_/Users/champ/Git/crows/src/habitat/garbage/Garbage.s"
	@echo "... C_/Users/champ/Git/crows/src/habitat/tree/Tree.obj"
	@echo "... C_/Users/champ/Git/crows/src/habitat/tree/Tree.i"
	@echo "... C_/Users/champ/Git/crows/src/habitat/tree/Tree.s"
	@echo "... C_/Users/champ/Git/crows/src/service/Manipulator.obj"
	@echo "... C_/Users/champ/Git/crows/src/service/Manipulator.i"
	@echo "... C_/Users/champ/Git/crows/src/service/Manipulator.s"
	@echo "... C_/Users/champ/Git/crows/src/service/PathFinder.obj"
	@echo "... C_/Users/champ/Git/crows/src/service/PathFinder.i"
	@echo "... C_/Users/champ/Git/crows/src/service/PathFinder.s"
	@echo "... C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.obj"
	@echo "... C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.i"
	@echo "... C_/Users/champ/Git/crows/src/sprite/AdvancedSprite.s"
	@echo "... C_/Users/champ/Git/crows/src/sprite/Sprite.obj"
	@echo "... C_/Users/champ/Git/crows/src/sprite/Sprite.i"
	@echo "... C_/Users/champ/Git/crows/src/sprite/Sprite.s"
	@echo "... C_/Users/champ/Git/crows/src/utility/DayManager.obj"
	@echo "... C_/Users/champ/Git/crows/src/utility/DayManager.i"
	@echo "... C_/Users/champ/Git/crows/src/utility/DayManager.s"
	@echo "... C_/Users/champ/Git/crows/src/utility/LevelMaker.obj"
	@echo "... C_/Users/champ/Git/crows/src/utility/LevelMaker.i"
	@echo "... C_/Users/champ/Git/crows/src/utility/LevelMaker.s"
	@echo "... opulence.obj"
	@echo "... opulence.i"
	@echo "... opulence.s"
	@echo "... src/entity/Entity.obj"
	@echo "... src/entity/Entity.i"
	@echo "... src/entity/Entity.s"
	@echo "... src/entity/animation/Animation.obj"
	@echo "... src/entity/animation/Animation.i"
	@echo "... src/entity/animation/Animation.s"
	@echo "... src/entity/camera/Camera.obj"
	@echo "... src/entity/camera/Camera.i"
	@echo "... src/entity/camera/Camera.s"
	@echo "... src/entity/camera/RtsCamera.obj"
	@echo "... src/entity/camera/RtsCamera.i"
	@echo "... src/entity/camera/RtsCamera.s"
	@echo "... src/entity/light/DirectionalLight.obj"
	@echo "... src/entity/light/DirectionalLight.i"
	@echo "... src/entity/light/DirectionalLight.s"
	@echo "... src/entity/light/Light.obj"
	@echo "... src/entity/light/Light.i"
	@echo "... src/entity/light/Light.s"
	@echo "... src/entity/light/PointLight.obj"
	@echo "... src/entity/light/PointLight.i"
	@echo "... src/entity/light/PointLight.s"
	@echo "... src/entity/model/Model.obj"
	@echo "... src/entity/model/Model.i"
	@echo "... src/entity/model/Model.s"
	@echo "... src/factory/CameraFactory.obj"
	@echo "... src/factory/CameraFactory.i"
	@echo "... src/factory/CameraFactory.s"
	@echo "... src/factory/LightFactory.obj"
	@echo "... src/factory/LightFactory.i"
	@echo "... src/factory/LightFactory.s"
	@echo "... src/factory/ModelFactory.obj"
	@echo "... src/factory/ModelFactory.i"
	@echo "... src/factory/ModelFactory.s"
	@echo "... src/loader/ObjLoader.obj"
	@echo "... src/loader/ObjLoader.i"
	@echo "... src/loader/ObjLoader.s"
	@echo "... src/loader/ShaderLoader.obj"
	@echo "... src/loader/ShaderLoader.i"
	@echo "... src/loader/ShaderLoader.s"
	@echo "... src/service/BufferCourier.obj"
	@echo "... src/service/BufferCourier.i"
	@echo "... src/service/BufferCourier.s"
	@echo "... src/service/GLManager.obj"
	@echo "... src/service/GLManager.i"
	@echo "... src/service/GLManager.s"
	@echo "... src/service/TimeManager.obj"
	@echo "... src/service/TimeManager.i"
	@echo "... src/service/TimeManager.s"
	@echo "... src/service/glew/glew.obj"
	@echo "... src/service/glew/glew.i"
	@echo "... src/service/glew/glew.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

